#!/bin/sh

### BEGIN INIT INFO
# Provides:          udpcontroller
# Required-Start:    $local_fs $syslog $remote_fs $network avrspi
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description: udpcontroller looper
### END INIT INFO

PIDFile="/var/run/udpcontrollerloop.pid"

case "$1" in
start)
        /usr/local/bin/udpcontroller.sh > /dev/null &
        echo $! > $PIDFile
        ;;
stop)
        read pid <$PIDFile
        kill -9 $pid
        rm $PIDFile
        read pid </var/run/udpcontroller.pid
        kill -9 $pid
        ;;
esac
exit 0;
